import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import NavBar from "@/components/navBar/navBar";
import Footer from "@/components/footer/footer";
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from "next/navigation";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'de'}];
}

// @ts-ignore
export default async function RootLayout({children, params: {locale}}) {
    let messages;
    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <NavBar/>
        {children}
        <Footer/>
        </NextIntlClientProvider>
        </body>
        </html>
    )
}
